version: '2.2'

services:
  postgresql:
    image: postgres:9.6
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # check if port 0x1538 (5432) is bound
      test: "cat /proc/net/tcp /proc/net/tcp6 | grep '1538'"
      interval: 10s
      timeout: 5s
      retries: 5

  simplewebserver:
    image: norbjd/simplewebserver:${SIMPLEWEBSERVER_VERSION}
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "4567:4567"
    restart: always
    environment:
      POSTGRESQL_HOSTPORT: postgresql:5432
      POSTGRESQL_DATABASE: test
      POSTGRESQL_USER: postgres

volumes:
  postgresql_db_data:
